
# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
gfcli:
  build: # 编译配置
    name: 'SuAsk'
    arch: "amd64"
    system: "linux,darwin,windows"
    mod: ""
    cgo: 0

  gen: # 自动生成 dao
    dao:
      - link: "mysql:root:123456@tcp(127.0.0.1:3306)/suask"
        descriptionTag: true
    enums:
      path: "internal/enum/enums.go"
  docker:
    build: "-a amd64 -s linux -p temp -ew"
    tagPrefixes:
      - my.image.pub/my-app